/* Public build (generated by tools/build_public.py): flyer previews hosted (bank details removed), ad slots hidden. */
window.SITE = {flyers: 'hosted', ads: false, contact: 'nfshold@gmail.com', freeUntil: '31 Dec 2026',
  formEndpoint: 'https://formsubmit.co/nfshold@gmail.com'};  /* Submit-a-shoot form -> emails nfshold@gmail.com (FormSubmit) */
