/* Public build (generated by tools/build_public.py): flyers link to the organiser's source, ad slots hidden. */
window.SITE = {flyers: 'link', ads: false, contact: 'nfshold@gmail.com', freeUntil: '31 Dec 2026'};
